### ISSUE TITLE
Erro utilizando mysql

### ISSUE THREAD

**Issue by tamiresana** [cami-la/academia-digital#31]
Oi Cami preciso de uma ajudinha para integrar o IntelliJ com o MySQL.
Eu mudei as configurações no pom.xml:

```
<dependency>
   <groupId>mysql</groupId>
   <artifactId>mysql-connector-java</artifactId>
   <scope>runtime</scope>
</dependency>
```

E mudei no arquivo application.yml:

```
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: tami
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
```

Mas quando rodo a aplicação aparece essa mensagem de erro:

`java.sql.SQLException: Access denied for user 'tami'@'localhost' (using password: YES)`

![image](https://user-images.githubusercontent.com/101058503/230741550-7c3939e1-96b8-480a-be78-7e0db67733b6.png)
