### ISSUE TITLE
Configuração do banco de dados

### ISSUE THREAD

**Issue by ghost** [cami-la/academia-digital#9]
Olá Camila!!!
Mulher, me socorre! O problema não são suas aulas, vc é ótima, mas não consegui configurar o banco de dados, então, ainda não tenho a real noção de como está o projeto. Não sei se é algo com o Postgres...eu uso Windows. Ainda vou ter que corrigir alguns erros que estão aparecendo, mas resolvi subir logo o projeto no GitHub, para caso vc queira dar uma olhada. Desde já agradeço!

**Comment by cami-la** [comment]
Oi, @RochelleMA. Tudo bem?
Você precisa ter o PostgreSQL instalado na sua máquina para poder criar o banco de dados.
Vou te mandar uma aula de PostgreSQL aqui da DIO que a expert ensina como instalar no Windows.
https://web.dio.me/course/introducao-a-postgresql/learning/5cf85563-d1cd-45df-8c74-370938c6f49c?back=/browse

Caso você não consiga, você também pode trocar o gerenciador de  banco de dados PostegreSQL para um banco de dados em memória, chamado H2.

1. No pom.xml troque a dependência do drive PostgreSQL para o H2:
![Screenshot from 2022-05-25 15-49-19](https://user-images.githubusercontent.com/64323124/170346122-52df383b-ad66-47b2-afb9-e253e7a943c1.png)
```
<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <scope>runtime</scope>
</dependency>
```
2. Altere as configurações do arquivo application.yml
![Screenshot from 2022-05-25 15-50-04](https://user-images.githubusercontent.com/64323124/170346273-9a069714-d884-4b5f-8cca-85659452125e.png)
```
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      console.settings.trace: false
      spring.h2.console.settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
```
3. Rode sua aplicação
![Screenshot from 2022-05-25 15-57-34](https://user-images.githubusercontent.com/64323124/170364176-faee9775-7c8c-41f0-b35a-13957de528cf.png)
4. Agora, você pode entrar no banco de dados H2 pela URL: http://localhost:8081/h2-console
5. Preencha as credenciais de acordo com as informações do arquivo application.yml
![Screenshot from 2022-05-25 15-53-51](https://user-images.githubusercontent.com/64323124/170347614-d9f835ac-21ff-45d3-aa2a-3cc7b785e19a.png)
6. Pronto, teste a conexão e depois conect:
![Screenshot from 2022-05-25 15-54-40](https://user-images.githubusercontent.com/64323124/170347840-6fbb21bd-2453-4ff4-b5bb-490dcd43bbf3.png)

Lembrando que esse banco de dados é em memória (volátil), logo, cada vez que você rodar a aplicação, você perde os dados.
Mas aqui para o treinamento, esse banco de dados é o suficiente.

Espero ter ajudado, e qualquer dúvida pode ir falando que vamos resolvendo juntas. (:

**Comment by ghost** [comment]
Obrigada Camila!
Deu certo 😉 consegui pelo Postgres mesmo, só teve uma coisinha... na tabela só apareceu o de alunos e matriculas 😅
![BD](https://user-images.githubusercontent.com/103073732/170577647-63cec900-af85-466e-a77f-4342316fef43.png)

**Comment by cami-la** [comment]
Parabéns, @RochelleMA!!!

Tenta fazer o seguinte, o arquivo de configuração application.yml:

```
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
```

1. Troca a propriedade do ddl-auto do hibernate para `create-drop`.
2. Roda novamente a aplicação
3. Confere se agora ele criou a tabela de Avaliação Fisica
4. Caso sim, volta para o ddl-aulto: `update`
